packages:
  - 'packages/*'
  - 'demos/*'

allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true

catalog:
  astro: ^6.4.4
  ky: ^2.0.2

catalogs:
  linting:
    '@arethetypeswrong/cli': 0.18.3
    publint: 0.3.21
  repo:
    tsdown: 0.22.1
    typescript: 6.0.3
