packages:
  - 'packages/*'
  - 'demos/*'

allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true

catalog:
  astro: ^7.0.0
  ky: ^2.0.2

catalogs:
  linting:
    '@arethetypeswrong/cli': 0.18.5
    publint: 0.3.24
  repo:
    tsdown: 0.22.14
    typescript: 6.0.3
