import { readFile, writeFile } from 'node:fs/promises'
import { defineConfig } from 'orval'

const openapiOutput = './src/openapi.ts'

async function useAstroZod() {
  const generated = await readFile(openapiOutput, 'utf8')

  await writeFile(
    openapiOutput,
    generated.replace('import * as zod from \'zod\';', 'import * as zod from \'astro/zod\''),
  )
}

export default defineConfig({
  clerk: {
    input: {
      target: 'https://raw.githubusercontent.com/clerk/openapi-specs/refs/heads/main/bapi/2025-11-10.yml',
    },
    hooks: {
      afterAllFilesWrite: useAstroZod,
    },
    output: {
      client: 'zod',
      mode: 'single',
      target: openapiOutput,
      override: {
        header: info => [
          'eslint-disable',
          `This file was auto-generated by Orval from the OpenAPI spec at ${info.title} (${info.version}).`,
          'Do not edit this file directly.',
        ],
      },
    },
  },
})
