name: Build Packages

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/pnpm-install
      - name: Build Packages
        run: pnpm run build
      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: packages/**/dist
          retention-days: 1
