name: Publint & Attw

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        uses: ./.github/actions/pnpm-install
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Run publint & attw
        run: pnpm run check
